# Introduction {-#intro}

The National Wildlife Refuge System (Refuge System) plays a unique role in connecting current and future generations to our nation’s rich natural heritage. A national wildlife refuge visit can instill a lasting passion for wildlife and wild lands. A carefully designed set of amenities, services, and recreational opportunities contributes to and enhances the visitor experience, making these important connections possible. Opportunities for outdoor recreation draw millions of people each year to national wildlife refuges. Many visitors enjoy hiking, paddling, wildlife viewing or nature photography. Others take part in heritage sports such as hunting and fishing. All these activities offer visitors a chance to unplug from the stresses of modern life and reconnect with their natural surroundings.

Established in 1903, and managed by the U.S. Fish and Wildlife Service (Service), The National Wildlife Refuge System is the leading network of protected lands and waters in the world specifically dedicated to the conservation of fish, wildlife, and their habitats. With 55 million visits per year, the Refuge System is committed to maintaining customer satisfaction and public engagement and strives to be the best place for people and wildlife to thrive [@USFWS2018]. 
As stated in the National Wildlife Refuge Improvement Act of 1997, the mission of the Refuge System is "to administer a national network of lands and waters for the conservation, management and, where appropriate, restoration of the fish, wildlife, and plant resources and their habitats within the United States for the benefit of present and future generations of Americans." Part of achieving this mission is the goal "to foster understanding and instill appreciation of the diversity and interconnectedness of fish, wildlife, and plants, and their habitats" and "to provide and enhance opportunities to participate in compatible wildlife-dependent recreation." There are 567 national wildlife refuges (refuges) and 38 wetland management districts nationwide, including possessions and territories in the Pacific and Caribbean, encompassing 95 million acres of land [@USFWS2018]. (QUESTION: Do we add marine national monuments and submerged lands and waters?) There is at least one refuge in every state and territory and within an hour’s drive of most major cities. This accessibility makes it easy for communities to enjoy their wildlife heritage. The Refuge System attracts more than 55 million visitors annually, including 39.6 million people who observe and photograph birds and wildlife, 9.7 million who hunt and fish, and 2.6 million teachers and students who use refuges as outdoor classrooms.
Understanding visitor perceptions of refuges and characterizing their experiences on refuges are critical elements of managing refuges and meeting the goals of the Refuge System. The President’s Management Agenda identifies the National Wildlife Refuge System as a high-impact service provider. Refuges work to maintain a high level of customer satisfaction by operating visitor centers; designing, installing and maintaining accessible trails; constructing viewing blinds; issuing special use permits; contracting with private concessions, and leveraging low recreation fees for facility improvements. 

Understanding changing visitor trends requires the same commitment to robust inventory and monitoring that the Refuge System has so diligently applied throughout its history. The national visitor survey effort provides managers, planners, visitor services specialists, and others with reliable baseline data. Knowing who visits refuges and what they do, how satisfied they are with their experience, and what their economic contributions are to the local community help refuge staff communicate the value of the refuge, set priorities, plan better, and track trends over time.
The purpose of the overall effort is to better understand visitor experiences and trip characteristics on refuges across Refuge System, to gauge visitors levels of satisfaction with existing recreational opportunities, and to garner feedback from visitors about their trips to inform the design of programs and facilities. The survey results are intended to inform performance, planning, budget, and communications goals. Results will also inform Comprehensive Conservation Plans (CCPs), visitor services, and transportation planning processes. Baseline information is also fundamental to the Service's Inventory and Monitoring Initiative, and can be used to assess changes over time [@USFWS2017].
Systematic monitoring of national wildlife refuges with 50,000 or more visitors per year will occur on a 5-year rotating basis (approx. 36 refuges/year). Visitors are contacted onsite, and the survey is administered by mail (with web option) once visitors return home. 
The national visitor survey is a collaborative effort between the Service, The Ohio State University (OSU), and American Conservation Experience (ACE).

########################
The National Wildlife Refuge System plays a unique role in connecting current and future generations to our nation’s rich natural heritage. A national wildlife refuge visit can instill a lasting passion for wildlife and wild lands. A carefully designed set of amenities, services, and recreational opportunities contributes to and enhances the visitor experience, making these important connections possible. Opportunities for outdoor recreation draw millions of people each year to national wildlife refuges. Many visitors enjoy hiking, paddling, wildlife viewing or nature photography. Others take part in heritage sports such as hunting and fishing. All these activities offer visitors a chance to unplug from the stresses of modern life and reconnect with their natural surroundings.

## The National Wildlife Refuge System{-}
Established in 1903, and managed by the U.S. Fish and Wildlife Service (Service), The National Wildlife Refuge System (Refuge System) is the leading network of protected lands and waters in the world specifically dedicated to the conservation of fish, wildlife, and their habitats. With 55 million visits per year, the Refuge System is committed to maintaining customer satisfaction and public engagement and strives to be the best place for people and wildlife to thrive [@USFWS2018]. 

As stated in the National Wildlife Refuge Improvement Act of 1997, the mission of the Refuge System is "to administer a national network of lands and waters for the conservation, management and, where appropriate, restoration of the fish, wildlife, and plant resources and their habitats within the United States for the benefit of present and future generations of Americans." Part of achieving this mission is the goal "to foster understanding and instill appreciation of the diversity and interconnectedness of fish, wildlife, and plants, and their habitats" and "to provide and enhance opportunities to participate in compatible wildlife-dependent recreation." There are 567 national wildlife refuges (refuges) and 38 wetland management districts nationwide, including possessions and territories in the Pacific and Caribbean, encompassing 95 million acres of land [@USFWS2018]. (QUESTION: Do we add marine national monuments and submerged lands and waters?) There is at least one refuge in every state and territory and within an hour’s drive of most major cities. This accessibility makes it easy for communities to enjoy their wildlife heritage. The Refuge System attracts more than 55 million visitors annually, including 39.6 million people who observe and photograph birds and wildlife, 9.7 million who hunt and fish, and 2.6 million teachers and students who use refuges as outdoor classrooms.

## Why a survey of refuge visitors?{-}
Understanding visitor perceptions of refuges and characterizing their experiences on refuges are critical elements of managing refuges and meeting the goals of the Refuge System. The President’s Management Agenda identifies the National Wildlife Refuge System as a high-impact service provider. Refuges work to maintain a high level of customer satisfaction by operating visitor centers; designing, installing and maintaining accessible trails; constructing viewing blinds; issuing special use permits; contracting with private concessions, and leveraging low recreation fees for facility improvements. 

Understanding changing visitor trends requires the same commitment to robust inventory and monitoring that the Refuge System has so diligently applied throughout its history. The national visitor survey effort provides managers, planners, visitor services specialists, and others with reliable baseline data. Knowing who visits refuges and what they do, how satisfied they are with their experience, and what their economic contributions are to the local community help refuge staff communicate the value of the refuge, set priorities, plan better, and track trends over time.

The purpose of the overall effort is to better understand visitor experiences and trip characteristics on refuges across Refuge System, to gauge visitors levels of satisfaction with existing recreational opportunities, and to garner feedback from visitors about their trips to inform the design of programs and facilities. The survey results are intended to inform performance, planning, budget, and communications goals. Results will also inform Comprehensive Conservation Plans (CCPs), visitor services, and transportation planning processes. Baseline information is also fundamental to the Service's Inventory and Monitoring Initiative, and can be used to assess changes over time [@USFWS2017].

Systematic monitoring of national wildlife refuges with 50,000 or more visitors per year will occur on a 5-year rotating basis (approx. 36 refuges/year). Visitors are contacted onsite, and the survey is administered by mail (with web option) once visitors return home. 

The national visitor survey is a collaborative effort between the Service, The Ohio State University (OSU), and American Conservation Experience (ACE). 

## Organization of This Report
