# Sampling and Surveying Methods{-#methods}

## Contacting Visitors{-}
Refuge staff identified two separate 14-day sampling periods, and one or more locations at which to sample, that best reflected the diversity of use and specific visitation patterns of each participating refuge. A standardized sampling schedule was created for all refuges that included eight randomly selected sampling shifts during each of the two sampling periods. Sampling shifts were four hour time bands, stratified across AM and PM as well as weekend and weekdays. In coordination with refuge staff, any necessary customizations were made to the standardized schedule to accommodate the identified sampling locations and to address specific spatial and temporal patterns of visitation.

Twenty-five visitors (18 years of age or older) per sampling shift were systematically selected, for a total of 375 willing participants per refuge (or 200 per sampling period) to ensure an adequate sample of completed surveys. When necessary, shifts were moved, added, or extended to overcome logistical limitations (for example, weather or low visitation at a particular site) in an effort to reach target numbers.

American Conservation Experience (ACE) interns and/or USFWS Human Dimensions staff (survey recruiters) contacted visitors onsite following a protocol provided by OSU that was designed to obtain a representative sample. Instructions included contacting visitors across the entire sampling shift (for example, every nth visitor for dense visitation, as often as possible for sparse visitation) and contacting only one person per group. Visitors were informed of the survey effort and asked to participate. Willing participants provided their name, mailing address, and preference for language (English or Spanish) and were given a small token incentive (for example, a magnet or sticker) for their participation. Survey recruiters were also instructed to record any refusals and then proceed with the sampling protocol.

All visitors that agreed onsite to fill out a survey received the same sequence of correspondence. This approach allowed for an assessment of visitors' likelihood of completing the survey by their preferred survey mode [@sexton2011]. Researchers at OSU sent the following materials to all visitors agreeing to participate who had not yet completed a survey at the time of each mailing [@dillman2014]: 

-	A postcard mailed within 10 days of the initial onsite contact thanking visitors for agreeing to participate in the survey and inviting them to complete the survey online. 
-	A packet mailed 14 days later consisting of a cover letter, survey, and postage paid envelope for returning a completed paper survey. 
-	A reminder postcard mailed 14 days later. 
-	A second packet mailed 7 days later consisting of another cover letter, survey, and postage paid envelope for returning a completed paper survey.

Each mailing included instructions for completing the survey online, so visitors had an opportunity to complete an online survey with each mailing. Those visitors indicating a preference for Spanish were sent Spanish versions of all correspondence (including the survey). Online survey data were exported and paper survey data were entered into Microsoft Excel using a standardized survey codebook and data entry procedure. All survey data were analyzed using Statistical Package for the Social Sciences (SPSS, v.23) software.^[Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government]

## Sampling at `r paste(params$RefugeName)`{-}

A total of `r length(nvs2018)` visitors agreed to participate in the survey during the two sampling periods at the identified locations at `r paste(params$RefugeName)` Table \@ref(tab:sampling-dates). In all, `r length(nvs2018)` visitors completed the survey for a `r length(nvs2018)/length(nvs2018)*100`% response rate, and 10% margin of error at the 95% confidence level.^[A margin of error of ± 5% at a 95% confidence level, for example, means that, if a reported percentage is 55%, then 95 out of 100 times, that sample estimate would fall between 50% and 60% if the same question was asked in the same way. The margin of error is calculated with an 80/20 response distribution, assuming that for a given dichotomous choice question, approximately 80% of respondents would select one choice and 20% would select the other choice [@salant1994].]

Table: (\#tab:sampling-dates)
```{r sampling-dates, echo=FALSE, tab.cap="Sampling dates"}
```

## Interpreting the Results{-}
The extent to which these results accurately represent the total population of visitors to this refuge is dependent on the number of visitors who completed the survey (sample size) and the ability of the variation resulting from that sample to reflect the beliefs and interests of different visitor user groups [@scheaffer1996]. The composition of the sample is dependent on the ability of the standardized sampling protocol for this study to account for the spatial and temporal patterns of visitor use unique to each refuge. Spatially, the geographical layout and public-use infrastructure varies widely across refuges. Some refuges can be accessed only through a single entrance, while others have multiple unmonitored access points across large expanses of land and water. As a result, the degree to which sampling locations effectively captured spatial patterns of visitor use will vary from refuge to refuge. Temporally, the two 14-day sampling periods may not have effectively captured all of the predominant visitor uses/activities on some refuges during the course of a year, which may result in certain survey measures such as visitors' self-reported "primary activity during their visit" reflecting a seasonality bias. Results contained within this report may not apply to visitors during all times of the year or to visitors who did not visit the survey locations.

In this report, visitors who responded to the survey are referred to simply as "visitors." However, when interpreting the results for `r paste(params$RefugeName)`, any potential spatial and temporal sampling limitation specific to this refuge needs to be considered when generalizing the results to the total population of visitors. For example, a refuge that sampled during a special event (for example, birding festival) held during the spring may have contacted a higher percentage of visitors who traveled greater than 50 miles to get to the refuge than the actual number of these people who would have visited throughout the calendar year (that is, oversampling of nonlocals). Another refuge may not have enough nonlocal visitors in the sample to adequately represent the beliefs and opinions of that group type. If the sample for a specific group type (for example, nonlocals, hunters, visitors who paid a fee) is too low (n < 30), a warning is included in the text. Finally, the term "this visit" is used to reference the visit during which people were contacted to participate in the survey. 
