# Conclusion {#concl}
These individual refuge results provide a summary of trip characteristics and experiences of a sample of visitors to `r paste(params$RefugeName)` during 2018 and are intended to inform decision-making efforts related to visitor services and transportation at this refuge. Additionally, the results from this survey can be used to inform planning efforts, such as a refuge's Comprehensive Conservation Plan. With an understanding of visitors' trip and activity characteristics, and visitor-satisfaction ratings with existing offerings, refuge managers are able to make informed decisions about possible modifications (whether a reduction or enhancement) to visitor facilities, services, or recreational opportunities. This information can help managers gauge demand for refuge opportunities and inform both implementation and communication strategies. Similarly, an awareness of visitors' satisfaction ratings with various refuge offerings can help determine if potential areas of concern need to be investigated further. As another example of the utility of these results, community relations may be improved or bolstered through an understanding of the value of the refuge to visitors, whether that value is attributed to an appreciation of the refuge's offerings, enjoyment of its recreational activities, or spending contributions of nonlocal visitors to the local economy. Such data about visitors and their experiences, in conjunction with an understanding of biophysical data on the refuge and its resources, can ensure that management decisions are consistent with the Refuge System mission while fostering a continued public interest in these special places. 

More information about the national visitor survey, including reports for all participating refuges, are available at go.osu.edu/refugereports. 

More information regarding the Service's Human Dimensions Branch can be found at https://www.fws.gov/Refuges/NaturalResourcePC/humanDimensions.html. 
